### ISSUE TITLE
NullPointerException by GraphicalDebugger when handling Success and AAHappened messages of dynamically launched nodes

### ISSUE THREAD

**Issue by anatoliykmetyuk** [AndreVanDelft/scala#26]
Consider following program:

``` scala
  def main(args: Array[String]) {
    val executor = ScriptExecutorFactory.createScriptExecutor(true)
    future {executor run _live()}
    executor.invokeFromET {executor.rootNode launch _doSomething()}
  }

  def script..
    live = (* doSomething *)

    doSomething = {println("Hello World!")}
```

Now, the dynamically launched process will be under <launched> node. When debugged with graphical debugger, it throws a NullPointerException when handling AAHappened and Success messages intended for root of dynamically launched subtree. Statically launched subtree behaves normally.

**Comment by anatoliykmetyuk** [comment]
Note that same problems are not observable when running without a debugger.

**Comment by AndreVanDelft** [comment]
Solved in TemplateChildNode (don't rely on parent!=null).
Owner of launched nodes still needs to be set.
